site_name: The Scratch Channel Docs
site_description: Official Documentation for The Scratch Channel.
repo_url: https://github.com/The-Scratch-Channel/tsc-web-client/
theme:
  name: readthedocs
  user_color_mode_toggle: true
  color_mode: default
