site_name: The Scratch Channel Docs
site_description: Official Documentation for The Scratch Channel.
repo_url: https://github.com/The-Scratch-Channel/tsc-web-client/
site_url: https://thescratchchannel.vercel.app/
theme:
  name: readthedocs
